import requests
import re


class Generator:
    """
        A class for generating text responses using a local Ollama API model.

        Attributes:
            model (str): The name of the model to use (default: "smollm:135m").

        Methods:
            generate(input_text):
                Sends the input_text to the Ollama API and returns the generated response.
    """

    def __init__(self, model="smollm:135m"):
        self.model = model
        self.instructions = "Answer briefly and politely. Maximum 15 seconds answers. "

    def generate(self, input_text):

        response = requests.post(
            "http://localhost:11434/api/generate",
            json={
                "model": self.model,
                "prompt": self.instructions+input_text,
                "stream": False
            }
        )
        print(f"You: {input_text}")

        if response.status_code == 200:
            output = clean_text(response.json()["response"])
            print("Ollama:", output)
        else:
            output = response.text
            print("Error:", output)

        return output


def clean_text(text):
    """
    Cleans the generated text by removing common LLM formatting artifacts.

    Args:
        text (str): The raw text generated by the language model.

    Returns:
        str: A cleaned version of the text, stripped of markdown artifacts and extra whitespace.
    """
    text = re.sub(r"[*_~`]+", "", text)
    text = re.sub(r"\s+", " ", text)
    text = re.sub(r'[“”"\'`´]+', "", text)
    text = re.sub(r"^(risposta|output|risp|reply|answer)[:\-]\s*", "", text, flags=re.IGNORECASE)

    return text.strip()
